name: Deploy

on:
 push:
   tags:
     - '*'
 workflow_dispatch:
   branches:
     - main
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          path: .
    
      - name: Build Image
        run: |
            make build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        run: |
            make push
