name: Deploy

on:
 workflow_dispatch:
    inputs:
        sdlversion:
          default: "2.28.3"
          description: "SDL Version"
  
jobs:
  build:
    name: Deploy - SDL v${{ github.event.inputs.sdlversion }}
    runs-on: ubuntu-latest
    environment: DockerHub

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          path: .
    
      - name: Build Image
        run: |
            SDL_VERSION=${{ github.event.inputs.sdlversion }} make build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        run: |
            make push
