name: Deploy

on:
 push:
   tags:
     - '*'
 workflow_dispatch:
   branches:
     - main
  
jobs:
  build:
    name: Deploy - SDL v${{ matrix.SDL_VERSION }}
    runs-on: ubuntu-latest
    environment: DockerHub
    strategy:
        fail-fast: false
        matrix:
          SDL_VERSION:
            - 2.28.3

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          path: .
    
      - name: Build Image
        run: |
            SDL_VERSION=${{matrix.SDL_VERSION}} make build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        run: |
            make push
